FROM mariadb
LABEL maintainer="Fran <inventado@gmail.com"

# Aniadir archivos al contenedor

ADD ./hosts /tmp/

# Aniadir variables de entorno

ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=mydb 
